### PR TITLE
Support Node 12 and minor CI related changes

### PR DESCRIPTION
**Pull request by nulltoken**
This brings a proposal to:
- Also support Node 12. Many projects still run on top of it and, although Node 14 LTS is soon to be released, not all of them will make the jump over the following days
- Teach the CI to also run against pull requests, to make this repository more contributing friendly
- Ensure through CI builds that this library works equally great on other platforms

### CODE REVIEW

**Comment by nulltoken** [comment]
@evanplaice Incidentally, adding the xplat build led me to discover than the project was relying on a deprecated package (https://www.npmjs.com/package/tsc) which was not properly behaving on all platforms.

I fixed it by rather targeting https://www.npmjs.com/package/typescript which led to eventually fix the typings to their proper signatures (cf. https://nodejs.org/docs/latest-v12.x/api/console.html#console_console_log_data_args and https://nodejs.org/docs/latest-v14.x/api/console.html#console_console_log_data_args)

image

**Comment by evanplaice** [comment]
Sorry about the delayed reply

> Also support Node 12. Many projects still run on top of it and, although Node 14 LTS is soon to be released, not all of them will make the jump over the following days

The Node 12.x line will never be supported in this org because it requires support for features released up-to 12.4.2. This org is forward looking, and will be maintained for decades. Adding additional steps to provide short-term backward compatibility isn't really worth the extra effort when 12.x is scheduled to be EOLd one year from now.

I'm actually planning to drop CommonJS support across all libs at that time (ie 12.x EOL date or 4/30/22) as well because documenting the usage of both module types is not good DX. I only added it because these projects have existed to support ESM in Node since 2 years before it was officially supported.

> Teach the CI to also run against pull requests, to make this repository more contributing friendly

Great addition. CI/CD needed some work. Once this lands, it'll need to be updated in every project in this org as well as the @vanillawc org.

> Ensure through CI builds that this library works equally great on other platforms

Nothing this, or any of the projects in this org does is OS-specific. If this were shipping platform-specific binaries I'd agree but everything here is standard JS.

For typescript, it's only used during the prerelease phase to type check and compile the typings. Good catch on tsc being deprecated. For whatever reason, npx doesn't work in OSX big sur. If you install typescript globally and call tsc from the npm scripts it works. That's the approach this lib uses now.

Ie. tsc isn't installed as a package, it's a command that gets introduced by installing typescript globally.

**Comment by nulltoken** [comment]
Thanks for the feedback

**Comment by evanplaice** [comment]
Did you want to take another stab at this?

CI running for every pull_request would be hugely beneficial

**Comment by nulltoken** [comment]
>CI running for every pull_request would be hugely beneficial

I know ;-) Feel free to cherry pick what may be of value to you.

Cheers!

**Comment by evanplaice** [comment]
Thank you 👍

**Comment by evanplaice** [comment]
The changes cherry-picked from this PR were released in [v2.0.5](https://github.com/vanillaes/mock-console/releases/tag/v2.0.5) and will be incorporated into the rest of the org via [this isse](https://github.com/vanillaes/vanillaes/issues/14)

**Pull request closed without merging**
